backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: 'src/assets' # Location where files will be stored in the repo
public_folder: 'src/assets' # The src attribute for uploaded media

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'src/pages/blog'
    create: true
    slug: '{{fields.url}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'URL Slug',
          name: 'url',
          widget: 'string',
          hint: 'Specify where the page will be written to. If you use "Blog Post", the post will be accessible from "blog/blog-post"',
        }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - {
          label: 'Date',
          name: 'date',
          widget: 'datetime',
          date_format: 'MM/DD/YYYY',
        }
      - { label: 'Tags', name: 'tags', widget: 'list', default: ['post'] }
      - { label: 'Featured Image', name: 'image', widget: 'image' }
      - { label: 'Image Caption', name: 'imageAlt', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - {
          label: 'Layout',
          name: 'layout',
          widget: 'hidden',
          # Change default layout when needed
          default: '../../layouts/BlogLayout.astro',
        }
